# Site settings
title: restful.ru
description: Сайт с примерами использования restful приложений 
keywords: rest, webservices, get, post, set, delete

baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://restful.ru' # the base hostname & protocol for your site

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
